//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buget.WebUI.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dutie
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public decimal Amount { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public int CreditorId { get; set; }
    
        public virtual Creditor Creditor { get; set; }
        public virtual User User { get; set; }
    }
}
